TAG_LIST = [
    # Object categories
    "kitchen_objects",
    "home_appliances",
    "food_containers",
    "tableware",
    "food",
    "beverages",
    "furniture",
    "bathroom_items",
    "cleaning_products",
    "textiles",

    "electronic_devices",
    "audio_video_equipment",
    "smart_home_devices",
    "plugs_and_cables",

    "clothing",
    "personal_accessories",
    "school_items",
    "office_items",
    "safety_items",
    "hygiene_items",

    "hand_tools",
    "power_tools",
    "construction_materials",
    "maintenance_materials",
    "gardening_tools",

    "sports_equipment",
    "board_games",
    "outdoor_equipment",
    "musical_instruments",

    "car_interior",
    "car_exterior",
    "motorcycles_and_bicycles",
    "public_transport",
    "vehicle_accessories",

    "object_manipulation_actions",
    "object_transport_actions",
    "opening_closing_actions",
    "assembly_disassembly_actions",
    "tool_usage_actions",
    "device_usage_actions",

    "walking",
    "running",
    "ascending_descending",
    "vehicle_movement",
    "driving",
    "outdoor_activity",

    "cooking_activity",
    "cleaning_activity",
    "tidying",
    "laundry",
    "home_care",

    "personal_hygiene",
    "dressing",
    "eating_drinking",
    "work_study",
    "technology_use",

    "manual_work",
    "technical_work",
    "office_work",
    "repair_construction",

    # Environments
    "kitchen_environment",
    "living_room",
    "bathroom_environment",
    "bedroom_environment",
    "storage_room",
    "closet_environment",

    "supermarket",
    "store",
    "restaurant_bar",
    "public_transport_environment",
    "gym",
    "public_office",

    "workshop",
    "laboratory",
    "construction_site",
    "office_environment",
    "industrial_warehouse",

    "street",
    "park",
    "parking_area",
    "residential_area",
    "natural_area",

    # Social interactions
    "conversation",
    "collaboration",
    "object_exchange",
    "teaching_explaining",
    "children_presence",
    "animals_presence",
    "crowded_scene",

    # Visual/dynamic features
    "hand_in_frame",
    "intense_motion",
    "camera_shake",
    "occlusions",
    "reflections",
    "light_changes",
    "close_view",
    "distant_view",
    "in_vehicle_view",
    "low_visibility",

    # Ego4D-specific recurring events
    "hand_object_interaction",
    "social_interaction",
    "domestic_tasks",
    "work_tasks",
    "indoor_navigation",
    "outdoor_navigation",
    "tool_interaction",
    "smartphone_use",
    "food_preparation",
    "vehicle_related_activity",
    "problem_solving"
]
